micronaut:
  application:
    name: backend
  security:
    enabled: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
# datasources:
#   default:
#     url: jdbc:postgresql://db:5432/postgres
#     driver-class-name: org.postgresql.Driver
#     username: postgres
#     password: mysecretpassword
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pokemondb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
